language: python
python:
  - "3.9"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential checkinstall
  - sudo apt-get install -y zlib1g-dev
  - wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
  - tar -xzvf openssl-1.1.1g.tar.gz
  - cd openssl-1.1.1g
  - ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
  - make
  - sudo make install
  - sudo mv /usr/bin/openssl /usr/bin/openssl.old
  - sudo ln -s /usr/local/openssl/bin/openssl /usr/bin/openssl
  - openssl version -a

install:
  - pip install -r requirements.txt

script:
  - pytest
