language: python
python:
  - "3.12"

services:
  - docker

before_install:
  - pip install docker-compose

# Comandos para instalar dependencias
install:
  - pip install -r requirements.txt

# Comandos para ejecutar pruebas
script:
  - pytest

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
