language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --only-upgrade openssl
  - openssl version -a
  - pip install docker-compose

# Comandos para instalar dependencias
install:
  - pip install -r requirements.txt

# Comandos para ejecutar pruebas
script:
  - pytest

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
